---
- name: Create cell0 mappings
  command: >
    docker exec nova_api nova-manage cell_v2 map_cell0
  register: map_cell0
  changed_when:
    - map_cell0 | success
    - '"Cell0 is already setup" not in map_cell0.stdout'
  failed_when:
    - map_cell0.rc != 0
  run_once: True
  delegate_to: "{{ groups['nova-api'][0] }}"

- include: bootstrap_service.yml
  when: map_cell0.changed

- name: Create base cell for legacy instances
  command: >
    docker exec nova_api nova-manage cell_v2 create_cell
  register: base_cell
  changed_when:
    - base_cell | success
  failed_when:
    - base_cell.rc != 0
    - '"already exists" not in base_cell.stdout'
  run_once: True
  delegate_to: "{{ groups['nova-api'][0] }}"

- name: Discovering nova hosts
  command: >
    docker exec nova_api nova-manage cell_v2 discover_hosts
  register: discover_hosts
  changed_when: False
  run_once: True
  delegate_to: "{{ groups['nova-api'][0] }}"
